// <auto-generated />
using System;
using EazyFind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EazyFind.Infrastructure.Migrations
{
    [DbContext(typeof(EazyFindDbContext))]
    [Migration("20251018011917_ProductAlertsSchemeFixe")]
    partial class ProductAlertsSchemeFixe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EazyFind.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Type")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("StoreCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("store_category_id");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("StoreCategoryId")
                        .HasDatabaseName("ix_products_store_category_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_products_url");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.ProductAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_checked_utc");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_price");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_price");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string[]>("StoreKeys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("store_keys")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id")
                        .HasName("pk_product_alerts");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_product_alerts_chat");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_product_alerts_active");

                    b.ToTable("product_alerts", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.ProductAlertMatch", b =>
                {
                    b.Property<long>("AlertId")
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("MatchedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("matched_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AlertId", "ProductId")
                        .HasName("pk_product_alert_matches");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_alert_matches_product_id");

                    b.ToTable("product_alert_matches", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Store", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Key")
                        .HasName("pk_stores");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stores_name");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.StoreCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("OriginalCategoryName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_category_name");

                    b.Property<string>("StoreKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_key");

                    b.HasKey("Id")
                        .HasName("pk_store_categories");

                    b.HasIndex("CategoryType")
                        .HasDatabaseName("ix_store_categories_category_type");

                    b.HasIndex("StoreKey")
                        .HasDatabaseName("ix_store_categories_store_key");

                    b.ToTable("store_categories", (string)null);
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Product", b =>
                {
                    b.HasOne("EazyFind.Domain.Entities.StoreCategory", "StoreCategory")
                        .WithMany("Products")
                        .HasForeignKey("StoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_store_categories_store_category_id");

                    b.Navigation("StoreCategory");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.ProductAlertMatch", b =>
                {
                    b.HasOne("EazyFind.Domain.Entities.ProductAlert", "Alert")
                        .WithMany("Matches")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_alert_matches_product_alerts_alert_id");

                    b.HasOne("EazyFind.Domain.Entities.Product", "Product")
                        .WithMany("Matches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_alert_matches_products_product_id");

                    b.Navigation("Alert");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.StoreCategory", b =>
                {
                    b.HasOne("EazyFind.Domain.Entities.Category", "Category")
                        .WithMany("StoreCategories")
                        .HasForeignKey("CategoryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_categories_categories_category_type");

                    b.HasOne("EazyFind.Domain.Entities.Store", "Store")
                        .WithMany("StoreCategories")
                        .HasForeignKey("StoreKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_categories_stores_store_key");

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Category", b =>
                {
                    b.Navigation("StoreCategories");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Product", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.ProductAlert", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.Store", b =>
                {
                    b.Navigation("StoreCategories");
                });

            modelBuilder.Entity("EazyFind.Domain.Entities.StoreCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
